package types

import (
	"fmt"
	gravitytypes "github.com/Gravity-Bridge/Gravity-Bridge/module/x/gravity/types"
	"strings"
)

const (
	// GravityDenomPrefix indicates the prefix for all assets minted by this module
	GravityNFTClassIDPrefix = ModuleName

	// GravityDenomSeparator is the separator for gravity denoms
	GravityNFTClassIDSeparator = ""

	// ETHContractAddressLen is the length of contract address strings
	ETHContractAddressLen = 42

	// GravityNFTClassIDLen is the length of the denoms generated by the gravity module
	GravityNFTClassIDLen = len(GravityNFTClassIDPrefix) + len(GravityNFTClassIDSeparator) + ETHContractAddressLen
)

/////////////////////////
// ERC721              //
/////////////////////////

// GravityERC721ClassId converts an EthAddress to a gravity cosmos class id for ERC721 tokens
func GravityERC721ClassId(tokenContract gravitytypes.EthAddress) string {
	return fmt.Sprintf("%s%s%s", GravityNFTClassIDPrefix, GravityNFTClassIDSeparator, strings.ToLower(tokenContract.GetAddress().Hex()))
}
